import buisnessBasics from '../../../assets/Home/HomeProducts/browseByCategory/buisnessBasics.svg';
import marketEssentials from '../../../assets/Home/HomeProducts/browseByCategory/marketEssentials.svg';
import packaging from '../../../assets/Home/HomeProducts/browseByCategory/packaging.svg';
import promotional from '../../../assets/Home/HomeProducts/browseByCategory/promotional.svg';
import realEstate from '../../../assets/Home/HomeProducts/browseByCategory/realEstate.svg';
import signs from '../../../assets/Home/HomeProducts/browseByCategory/signs.svg';
import stickers from '../../../assets/Home/HomeProducts/browseByCategory/stickers.svg';

export const browseByCategoryFakeData = [
	{
		id: 0,
		icon: buisnessBasics,
		name: 'Business Basics',
		subData: [
			'Appointment Cards',
			'Business Cards',
			'Carbonless Forms',
			'Letterhead',
			'Envelopes',
			'Notepads',
			'Pocket Folders',
			'Post-its',
			'Rubber Stamps',
			'Sales Sheets',
			'Shipping & Mailing Labels',
			'Statement Stuffers',
		],
	},
	{
		id: 1,
		icon: marketEssentials,
		name: 'Market Essentials',
		subData: [
			'Appointment Cards',
			'Business Cards',
			'Carbonless Forms',
			'Letterhead',
			'Envelopes',
			'Notepads',
			'Pocket Folders',
			'Post-its',
			'Rubber Stamps',
			'Sales Sheets',
			'Shipping & Mailing Labels',
			'Statement Stuffers',
		],
	},
	{
		id: 2,
		icon: packaging,
		name: 'Packaging & Retail',
		subData: [
			'Appointment Cards',
			'Business Cards',
			'Carbonless Forms',
			'Letterhead',
			'Envelopes',
			'Notepads',
			'Pocket Folders',
			'Post-its',
			'Rubber Stamps',
			'Sales Sheets',
			'Shipping & Mailing Labels',
			'Statement Stuffers',
		],
	},
	{
		id: 3,
		icon: promotional,
		name: 'Promotional & Events',
		subData: [
			'Appointment Cards',
			'Business Cards',
			'Carbonless Forms',
			'Letterhead',
			'Envelopes',
			'Notepads',
			'Pocket Folders',
			'Post-its',
			'Rubber Stamps',
			'Sales Sheets',
			'Shipping & Mailing Labels',
			'Statement Stuffers',
		],
	},

	{
		id: 4,
		icon: realEstate,
		name: 'Real Estate Products',
		subData: [
			'Appointment Cards',
			'Business Cards',
			'Carbonless Forms',
			'Letterhead',
			'Envelopes',
			'Notepads',
			'Pocket Folders',
			'Post-its',
			'Rubber Stamps',
			'Sales Sheets',
			'Shipping & Mailing Labels',
			'Statement Stuffers',
		],
	},
	{
		id: 5,
		icon: signs,
		name: 'Signs,Banners & Displays',
		subData: [
			'Appointment Cards',
			'Business Cards',
			'Carbonless Forms',
			'Letterhead',
			'Envelopes',
			'Notepads',
			'Pocket Folders',
			'Post-its',
			'Rubber Stamps',
			'Sales Sheets',
			'Shipping & Mailing Labels',
			'Statement Stuffers',
		],
	},
	{
		id: 6,
		icon: stickers,
		name: 'Stickers & Labels',
		subData: [
			'Appointment Cards11',
			'Business Cards22',
			'Carbonless Forms423',
			'Letterhead4234',
			'Envelopes243',
			'Notepads423',
			'Pocket Folders423',
			'Post-its534',
			'Rubber Stamps534',
			'Sales Sheets',
			'Shipping & Mailing Label534',
			'Statement Stuffers345',
		],
	},
];
